# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db299f01d5c28b2b6b8956e35475821b104d52d5f5539ccc8f316b45f5362f44d17bf200f60d1efbe73febfbaa71fe8cf20ceb30233d1e31263a0f8c438a5b78

test:
  secret_key_base: b780c6d0fb2dc298d5191789a0bc583136754bbc739a86cf2aef60fa8a434290440a36c716b686db7c106901570eb3c8cb9fec0e6f40cf3146c4e17a0899605f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
